project:
  type: website
  output-dir: docs

website:
  title: "stat386stonks"
  site-url: "https://chamiltonb8.github.io/final_project/"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Tutorial.qmd
        text: Tutorial
      - href: Documentation.qmd
        text: Documentation

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
