project:
  type: website
  output-dir: docs

website:
  title: "stat386stonks"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: tutorial.qmd
        text: Tutorial
      - href: documentation.qmd
        text: Documentation
      - href: reference.qmd
        text: API Reference

format:
  html:
    theme: cosmo
    css: style.css
    toc: true
